version: '3.8'

services:
  app:
    build: .
    container_name: sga-tec-test
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - redis
    environment:
      MONGODB_URI: mongodb://mongodb:27017/nest
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  mongo-data:
